#!/usr/bin/env python3
"""labsentry-report: turn a labsentry scan JSON into a prioritized markdown fix-list.

Pure stdlib (no deps). Reads the JSON catalog produced by:
    labsentry scan --roots <roots> --db audit.db --json audit.json

Outputs a 1-page prioritized report: root causes, exact commands, rollback.
This is the engine behind the "Lab Doctor" paid audit offer.

Usage:  python3 report.py audit.json > report.md
"""
import json
import sys
import os
from collections import defaultdict

VIOLATION_FIX = {
    "rootfs-runtime": (
        "Native build/runtime cache landed on the root filesystem instead of the "
        "designated storage mount. Move it to NVMe/ext4 and symlink, or repoint the tool.",
        "mv <path> /mnt/ai-storage/<safe-name> && ln -s /mnt/ai-storage/<safe-name> <path>",
        "rm <path>  # if symlink, then restore original dir",
    ),
    "storage-blob-on-root": (
        "Large model/blob stored on rootfs; should live on the storage mount.",
        "mv <path> /mnt/ai-storage/models/ && ln -s /mnt/ai-storage/models/<base> <path>",
        "mv /mnt/ai-storage/models/<base> <original-path>",
    ),
    "duplicate": (
        "Duplicate of another asset (same sha256) — wasted disk.",
        "Verify both open identically, then: rm <duplicate-path>",
        "cp <duplicate-path> <duplicate-path>.bak  (keep backup until verified)",
    ),
    "port-conflict": (
        "Two services claimed the same port (e.g. Snap Prometheus on 9090 vs Docker).",
        "sudo snap stop prometheus   # frees 9090; or move the other service to 9091",
        "sudo snap start prometheus",
    ),
}


def gb(n):
    return f"{n/1e9:.2f} GB"


def build_report(data, json_path):
    gen = data.get("generated", "unknown")
    assets = data.get("assets", [])
    lines = []
    lines.append("# Lab Doctor — AI-Lab Audit Report")
    lines.append("")
    lines.append(f"_Generated: {gen}_  ")
    lines.append(f"_Source catalog: `{os.path.basename(json_path)}`_")
    lines.append("")

    # group
    by_viol = defaultdict(list)
    dup_groups = defaultdict(list)
    ports = []
    total_bytes = 0
    for a in assets:
        total_bytes += a.get("size", 0) or 0
        v = a.get("violation")
        if v:
            by_viol[v].append(a)
        if v == "duplicate":
            dup_groups[a.get("sha256")].append(a)
        if "port" in str(a.get("type", "")) or "conflict" in str(v):
            ports.append(a)

    lines.append("## Summary")
    lines.append("")
    lines.append(f"- Assets scanned: **{len(assets)}**")
    lines.append(f"- Total size: **{gb(total_bytes)}**")
    lines.append(f"- Violations: **{sum(len(v) for v in by_viol.values())}**")
    lines.append(f"- Duplicate groups: **{sum(1 for g in dup_groups.values() if len(g) > 1)}**")
    lines.append(f"- Port conflicts: **{len([p for p in ports if 'conflict' in str(p.get('violation'))])}**")
    lines.append("")

    # priority order
    priority = ["port-conflict", "rootfs-runtime", "storage-blob-on-root", "duplicate"]
    lines.append("## Prioritized Fix List")
    lines.append("")
    any_fix = False
    for v in priority:
        items = by_viol.get(v, [])
        if not items:
            continue
        any_fix = True
        fix = VIOLATION_FIX.get(v)
        title = v.replace("-", " ").title()
        lines.append(f"### {title} ({len(items)})")
        lines.append("")
        if fix:
            lines.append(f"**Root cause:** {fix[0]}")
            lines.append("")
            lines.append(f"**Fix:** `{fix[1]}`")
            lines.append("")
            lines.append(f"**Rollback:** `{fix[2]}`")
            lines.append("")
        for a in items[:10]:
            p = a.get("path", "?")
            lines.append(f"- `{p}` ({a.get('type', '?')}, {gb(a.get('size', 0))})")
        if len(items) > 10:
            lines.append(f"- …and {len(items) - 10} more")
        lines.append("")

    if not any_fix:
        lines.append("_No violations detected. Your lab is clean._")
        lines.append("")

    # duplication detail
    dup_real = {k: v for k, v in dup_groups.items() if len(v) > 1}
    if dup_real:
        lines.append("## Duplicate Assets (wasted disk)")
        lines.append("")
        wasted = 0
        for sha, grp in dup_real.items():
            kept = grp[0]
            wasted += sum(a.get("size", 0) for a in grp[1:])
            lines.append(f"- sha256 `{sha[:12]}…` — keep `{kept.get('path')}`, remove {len(grp) - 1}:")
            for a in grp[1:]:
                lines.append(f"    - `{a.get('path')}` ({gb(a.get('size', 0))})")
        lines.append("")
        lines.append(f"**Potential reclaim: {gb(wasted)}**")
        lines.append("")

    lines.append("---")
    lines.append("_Report generated by labsentry-report (Lab Doctor). Verify each command before running._")
    return "\n".join(lines)


def main():
    if len(sys.argv) < 2:
        sys.stderr.write("usage: report.py <audit.json>\n")
        sys.exit(2)
    path = sys.argv[1]
    with open(path) as f:
        data = json.load(f)
    print(build_report(data, path))


if __name__ == "__main__":
    main()
